name: crop_doc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  file_picker: ^4.0.0
  tflite_flutter: any
  http: ^0.13.3
  mime: ^1.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/plant-disease_doc_.tflite

  uses-material-design: true
